---
title: "mysql_to_r"
output: html_document
date: '2022-10-24'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Prep work 
Loading in Data 
```{r, eval = FALSE}
#of02 <- read.csv("export/opafy02nid.csv", nrows = 10) #3909 
#of03 <- read.csv("export/opafy03nid.csv", nrows = 10) #6501
of04 <- read.csv("export/opafy04nid.csv", nrows = 2) #17646
of05 <- read.csv("export/opafy05nid.csv", nrows = 2) #14907
#of06 <- read.csv("export/opafy06nid.csv", nrows = 10) #9929
of07 <- read.csv("export/opafy07nid.csv", nrows = 2) #24528
of08 <- read.csv("export/opafy08nid.csv", nrows = 2) #15341
of09 <- read.csv("export/opafy09nid.csv", nrows = 2) #15423
of10 <- read.csv("export/opafy10nid.csv", nrows = 2)
of11 <- read.csv("export/opafy11nid.csv", nrows = 2)
of12 <- read.csv("export/opafy12nid.csv", nrows = 2)
of13 <- read.csv("export/opafy13nid.csv", nrows = 2)
of14 <- read.csv("export/opafy14nid.csv", nrows = 2)
of15 <- read.csv("export/opafy15nid.csv", nrows = 2)
of16 <- read.csv("export/opafy16nid.csv", nrows = 2)
of17 <- read.csv("export/opafy17nid.csv", nrows = 2)
of18 <- read.csv("export/opafy18nid.csv", nrows = 2)
of19 <- read.csv("export/opafy19nid.csv", nrows = 2)
of20 <- read.csv("export/opafy20nid.csv", nrows = 2)
of21 <- read.csv("export/opafy21nid.csv", nrows = 2)
```

SQL Text
```{r, eval = FALSE}
#colnames(of02)[71] <- 'INOUT_edited'
test <- colnames(of02)
test <- paste(test, 'varchar(30)', sep = ' ')
test <- toString(test)
test <- paste( "Create table opafy02nid( ",test, " );")
#write.table(test, file = 'opafy02nid_sql.txt')
```

# GOOGLE BIG QUERY 
https://solutions.rstudio.com/db/databases/big-query/ 

### BigQuery Sql
```{r}
df <- read.csv("new_data/opafy13nid_2.csv", nrows = 2)
sql <- colnames(df) 
sql <- paste(sql,":STRING")
sql <- paste(sql, collapse= ', ')
write.table(sql, file = 'big_query.txt')
```

### BigQuery connection 
```{r}
library(bigrquery)
library(DBI)

con <- dbConnect(
  bigrquery::bigquery(),
  project = "balmy-coral-330818",
  dataset = "bqtest"
  )


```

### Example code 
References: 
https://solutions.rstudio.com/db/getting-started/database-queries/ 
https://dbi.r-dbi.org/reference/dbsendquery 
https://bigrquery.r-dbi.org/

```{r}
dbListTables(con)

query = dbSendQuery(con, "select `REASON1` from opafy02nid limit 2")
data <-  dbFetch(query)
```




# MySQL 
```{r}
library(RMySQL)
library(tidyverse)
```

MySQL Connection 
```{r, eval=FALSE}
mysqlconnection = dbConnect(RMySQL::MySQL(),
                            dbname='doherty',
                            host='34.69.48.201',
                            port=3306,
                            user='root')

#list tables 
dbListTables(mysqlconnection)
```

Sample Query 
```{r, eval=FALSE}
io_query = dbSendQuery(mysqlconnection, "select * from io")
#n = -1 returns all rows 
data.frame = fetch(io_query, n = -1)
```


