---
title: "Region Breakdown"
output: html_document
date: "2023-10-31"
---

```{r setup, include=FALSE}

library(tidyverse)
library(flextable)
library(janitor)
library(scales)
library(readxl)

data <- read_csv(here::here("data/io.csv"))


postprotect <- data %>% 
  filter(postprotect) #06-24-04

postbooker <- data %>% 
  filter(postbooker) #dates are not right #12-10-2007

postgall <- data %>% 
  filter(postgall)

postreport <- data %>% 
  filter(postreport)

present <- data %>% 
  filter(present)

highlight_above_avg <- function(ft){
  ft %>% 
    bg(i = ~ `Black Male`>Overall, 
     j = ~ `Black Male`, 
     bg="#Fba894") %>% 
    bg(i = ~ `Hispanic Male`>Overall, 
       j = ~ `Hispanic Male`, 
       bg="#Fba894") %>% 
    bg(i = ~ `White Male`>Overall, 
       j = ~ `White Male`, 
       bg="#Fba894") %>% 
    bg(i = ~ `Other Male`>Overall, 
       j = ~ `Other Male`, 
       bg="#Fba894") %>% 
    bg(i = ~ `Black Female`>Overall, 
       j = ~ `Black Female`, 
       bg="#Fba894") %>% 
    bg(i = ~ `Hispanic Female`>Overall, 
       j = ~ `Hispanic Female`, 
       bg="#Fba894") %>% 
    bg(i = ~ `White Female`>Overall, 
       j = ~ `White Female`, 
       bg="#Fba894") %>% 
    bg(i = ~ `Other Female`>Overall, 
       j = ~ `Other Female`, 
       bg="#Fba894")
}
```


## Average Sentence, by Federal District and Period 



```{r}


dem_avg <- function(df){
  df %>% 
    group_by(fedNum) %>% 
    summarize(avg_sent = mean(SENSPLT0, na.rm=T))
}

list_periods <- list(postprotect, postbooker, postgall, postreport, present)

avg_sent_dem_tbl <- map(list_periods, dem_avg) %>% 
  bind_rows(.id = "Period") %>% 
  mutate(avg_sent = round(avg_sent),
         Period = recode(as.character(Period),
                         "1" = "Protect", "2" = "Booker", "3" = "Gall", "4" = "Post-Report", "5" = "Present")) %>% 
  pivot_wider(names_from = Period, values_from = avg_sent) %>% 
  rename("Group" = fedNum)

avg_sent_dem_tbl %>% 
  flextable()


```

Because most of the data is labeled under present day, we will only be considering this time period for region breakdown. 


## Average Sentence by Demographic and Federal District
```{r}
par(mfrow=c(2,2))
df <- present%>% 
  select(SENSPLT0, fedNum, racesex_clean) %>% 
  group_by(fedNum, racesex_clean) %>% 
  summarize(avg_sent = round(mean(SENSPLT0, na.rm = T))) %>% 
  ungroup() %>% 
  pivot_wider(names_from = racesex_clean, values_from = avg_sent) 

df %>% flextable()


# Loop through rows and create bar charts
for (i in 1:nrow(df)) {
  # Select data for the current row
  current_row <- df[i, ]
  
  # Extract the fedNum and remove it from the data for plotting
  fedNum <- current_row$fedNum
  current_row <- current_row[-1]
  
  # Create a bar chart for the current row
  barplot(as.matrix(current_row), names.arg = names(current_row),
          main = paste("Bar Chart for fedNum =", fedNum), legend = TRUE,cex.names= 0.6,las =2 )
}

# Get the column names excluding the first column (fedNum)
columns <- names(df)[-1]


# Loop through columns and create bar charts
for (col in columns) {
  # Create a bar chart for the current column
  barplot(df[[col]], names.arg = df$fedNum,
          main = paste("Bar Chart for", col),
          xlab = "fedNum", ylab = col,
          col = "steelblue", cex.names = .9)
}

```

## Average Sentence by Crime Type and Federal District 
```{r}

ggplot( data = present , aes(fedNum, SENSPLT0)) + 
  geom_boxplot() + facet_wrap(~fedNum)

boxplot(SENSPLT0 ~ fedNum, data = present, 
        outline = FALSE)

crime_df <- present%>% 
  select(SENSPLT0, fedNum, crime_type) %>% 
  group_by(fedNum, crime_type) %>% 
  summarize(avg_sent = round(mean(SENSPLT0, na.rm = T))) %>% 
  ungroup() %>% 
  pivot_wider(names_from = crime_type, values_from = avg_sent) 

crime_df %>% flextable()

```



```{r}
par(mfrow = c(2,2))
drug <-  present %>% 
  filter(crime_type== "Drug Trafficking") %>% 
  select(crime_type, racesex_clean, fedNum, SENSPLT0) %>% 
  group_by(racesex_clean, fedNum) %>% 
  summarize(avg_sent = round(mean(SENSPLT0, na.rm = T))) %>% 
  ungroup() %>% 
  pivot_wider(names_from = fedNum, values_from = avg_sent)



# Get the column names excluding the first column (fedNum)
columns <- names(drug)[-1]
# Loop through columns and create bar charts
for (col in columns) {
  # Create a bar chart for the current column
  barplot(drug[[col]], names.arg = drug$racesex_clean,
          main = paste("Bar Chart for", col), ylab = col,
          col = "cornflowerblue", cex.names = .7, las = 2)
}
```




# 

```{r}
model2filter <- function(df){
  df %>% 
    select(SENSPLT0,
           logsplit,
           logmin,
           violent,
           drugtraff,
           sexual2,
           porn,
           immigration,
           othtype2,
           whitecoll,
           upward,
           downdep,
           subasst,
           mandmin2,
           NEWCNVTN,
           custody,
           racesex,
           racesex_clean,
           agedummy,
           educ,
           citizen, 
           fedNum) %>% 
    filter(if_all(everything(), ~ !is.na(.)))
}
```





```{r}
present %>% model2filter()
```
```{r}

model2 <- function(df){
  lm(logsplit ~ logmin + 
               drugtraff +
               sexual2 + 
               porn +
               immigration +
               othtype2 +
               whitecoll +
               upward +
               downdep +
               subasst +
               mandmin2 +
               NEWCNVTN +
               custody +
               relevel(factor(racesex), ref = 8) +
               agedummy +
               educ +
               citizen + 
               fedNum,
             df)
}


```


```{r}
present %>% model2filter() %>% model2()
```

