---
title: "2017-2021 Aggravating and Mitigating Role Adjustments"
fontsize: 12pt
output: 
  html_document:
    toc: yes
    toc_float:
      collapsed: no
    toc_depth: 5
    number_sections: true
  pdf_document: default
urlcolor: magenta
editor_options: 
  chunk_output_type: inline

---
Packages
```{r}
library(tidyverse)
library(flextable)
```


Data
```{r}
am <- read_csv("~/Downloads/doherty_research/data_files/io_2017_2021.csv")
am <- am%>%  mutate(crime_type = crime_type %>% 
           str_replace("Immigration", "Immig.") %>% 
           str_replace("Drug Trafficking", "Drug Traff."))
```

Functions
```{r}
flextable_my <- function(x){
  x %>% 
    flextable() %>% 
    width(width = .7) %>% 
    fontsize(size = 8, part = "header") %>% 
    fontsize(size = 8, part = "body")
}

```

# Mitigating Role Adjustments 

```{r}

amdata_tbl <- am %>% 
  filter(!is.na(mitigate) | !is.na(aggravate)) %>% 
  filter(!is.na(racesex) & !is.na(crime_type)) %>% 
  group_by(racesex_clean, crime_type) %>% 
  summarize(total = n(),
            n_agg = sum(aggravate, na.rm=T),
            n_mit = sum(mitigate, na.rm=T)) %>%
  mutate(pct_agg = round(n_agg/total, 3),
         pct_mit = round(n_mit/total, 3)) 

amdata_tbl %>% 
  select(crime_type, racesex_clean, n_mit) %>% 
  pivot_wider(names_from = "crime_type", values_from = n_mit) %>% 
  rename(" " = racesex_clean) %>% 
  flextable_my() %>% 
  set_caption("Number of Mitigating Role Adjustments, FY2017-FY2021")

```
<br> 
```{r}
amdata_tbl %>% 
  select(crime_type, racesex_clean, pct_mit) %>% 
  pivot_wider(names_from = "crime_type", values_from = pct_mit) %>% 
  rename(" " = racesex_clean) %>% 
  flextable_my() %>% 
  set_caption("Portion of Mitigating Role Adjustments, FY2017-FY2021")
```



<br> 
<br> 
<br> 

# Aggravating Role Adjustments 
```{r}
amdata_tbl %>% 
  select(crime_type, racesex_clean, n_agg) %>% 
  pivot_wider(names_from = "crime_type", values_from = n_agg) %>% 
  rename(" " = racesex_clean) %>% 
  flextable_my() %>% 
  set_caption("Number of Aggravating Role Adjustments, FY2017-FY2021")
  
```
<br> 
```{r}
amdata_tbl %>% 
  select(crime_type, racesex_clean, pct_agg) %>% 
  pivot_wider(names_from = "crime_type", values_from = pct_agg) %>% 
  rename(" " = racesex_clean) %>% 
  flextable_my() %>% 
  set_caption("Portion of Aggravating Role Adjustments, FY2017-FY2021")
```


<br>
<br>
<br> 

# Mitigating Role Departures 
```{r}
amdata_tbl %>% 
  ggplot() +
  geom_col(aes(x = racesex_clean, y = pct_mit, fill = racesex_clean))+
  theme_minimal()+
  labs(title = "Portion of Mitigating Role Departures by Demographic, Grouped by Crime Type")+
  theme(#text = element_text(size = 20),
        title = element_text(size = 8),
        legend.position = "none",
        axis.text.x=element_text(angle=-90),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank())+
  facet_wrap(~crime_type)
```
<br> 
```{r}
amdata_tbl %>% 
  ggplot() +
  geom_col(aes(x = crime_type, y = pct_mit, fill = crime_type))+
  theme_minimal()+
  labs(title = "Portion of Mitigating Role Departures by Crime Type, Grouped by Demographic")+
  theme(#text = element_text(size = 20),
        title = element_text(size = 8),
        legend.position = "none",
        axis.text.x=element_text(angle=-90),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank())+
  scale_fill_brewer(palette = "Dark2")+
  facet_wrap(~racesex_clean, ncol = 2)

```
<br>
<br>
<br>

# Aggravating Role Departures 
```{r}
amdata_tbl %>% 
  ggplot() +
  geom_col(aes(x = racesex_clean, y = pct_agg, fill = racesex_clean))+
  theme_minimal()+
  labs(title = "Portion of Aggravating Role Departures by Demographic, Grouped by Crime Type")+
  theme(#text = element_text(size = 20),
        title = element_text(size = 8),
        legend.position = "none",
        axis.text.x=element_text(angle=-90),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank())+
  facet_wrap(~crime_type)
```
<br> 
```{r}
amdata_tbl %>% 
  ggplot() +
  geom_col(aes(x = crime_type, y = pct_agg, fill = crime_type))+
  theme_minimal()+
  labs(title = "Portion of Aggravating Role Departures by Crime Type, Grouped by Demographic")+
  theme(title = element_text(size = 8),
        legend.position = "none",
        axis.text.x=element_text(angle=-90),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank())+
  scale_fill_brewer(palette = "Dark2")+
  facet_wrap(~racesex_clean, ncol = 2)
```
<br>
<br>
<br>



