---
title: "family"
output: html_document
date: '2022-12-28'
---
```{r}
library(bigrquery)
library(DBI)
library(tidyverse)
library(glue)
library(janitor)
```

REAS1-REASX
- 17 (5H1.6) Family ties and responsibilities
- 18 (5H1.6) Community ties

fy17 = 25 
fy18 = 35
fy19 = 28
fy20 = 26 
fy21 = 30 

```{r}
con <- dbConnect(
  bigrquery::bigquery(),
  project = "balmy-coral-330818",
  dataset = "bqtest"
  )


```

```{r}
aggregate_reasons <- function(df, num){
  hold <- c()
  for (i in 1:num){
    hold[i] = paste('{REAS', as.character(i), '}', sep = '')
  }
  hold <- paste(hold, collapse = ' ')
  df %>% 
    #rename_all(str_to_upper) %>% 
    mutate(reason = glue(hold) %>% 
           str_remove_all("NA") %>% 
           str_squish(),
         .keep = "unused") %>% 
    remove_empty()
}


```


2017 

```{r}
query2017 = dbSendQuery(con, "select `id`,`REAS1`, `REAS2`, `REAS3`, `REAS4`, `REAS5`, `REAS6`, `REAS7`, `REAS8`, `REAS9`, `REAS10`, `REAS11`, `REAS12`, `REAS13`, `REAS14`, `REAS15`, `REAS16`, `REAS17`,`REAS18`,`REAS19`,`REAS20`,`REAS21`, `REAS22`, `REAS23`, `REAS24`, `REAS25`  from fy17_1")
data2017 <-  dbFetch(query2017)
df2017 <- aggregate_reasons(data2017, 25) 


df2017 <- df2017 %>% select(id, reason)
df2017$family <- str_detect(df2017$reason, "\\b17\\b")
```




2018

```{r}
query2018 = dbSendQuery(con, "select `id`,`REAS1`, `REAS2`, `REAS3`, `REAS4`, `REAS5`, `REAS6`, `REAS7`, `REAS8`, `REAS9`, `REAS10`, `REAS11`, `REAS12`, `REAS13`, `REAS14`, `REAS15`, `REAS16`, `REAS17`,`REAS18`,`REAS19`,`REAS20`,`REAS21`, `REAS22`, `REAS23`, `REAS24`, `REAS25`,`REAS26`,`REAS27`,`REAS28`,`REAS29`,`REAS30`,`REAS31`,`REAS32`,`REAS33`,`REAS34`,`REAS35`  from fy18_1")
data2018 <-  dbFetch(query2018)

df2018 <- aggregate_reasons(data2018) 
df2018 <- df2018 %>% select(id, reason)
df2018$family <- str_detect(df2018$reason, "\\b17\\b")
```

