---
title: "Prep: Splitting the Datasets"
output: html_document

---

# Packages 
```{r}
library(tidyverse)
```

# Regarding 2002, 2003, and 2006 
2002, 2003, and 2006 had less than 10,000 columns. 
Thus, they did not need any modification 

# 2004 
```{r, eval = FALSE}
fy04 <- read_csv("Downloads/research/export/opafy04nid.csv",guess_max = 50000) #17646
fy04_1 <- fy04[,1:9998]
fy04_1$id <- seq.int(nrow(fy04_1))
write.csv(fy04_1, "~/Downloads/research/new_data_r/fy04_1.csv")
fy04_2 <- fy04[,9999:17646]
fy04_2$id <- seq.int(nrow(fy04_2))
#write.csv(fy04_2, "~/Downloads/research/new_data_r/fy04_2.csv")

```


# 2005 
```{r, eval = FALSE}
fy05 <- read_csv("Downloads/research/export/opafy05nid.csv", guess_max = 50000)#14907
fy05_1 <- fy05[,1:9998] 
fy05_2 <- fy05[,9999:14907]
fy05_1$id <- seq.int(nrow(fy05_1))
fy05_2$id <- seq.int(nrow(fy05_2))
#write.csv(fy05_1, "~/Downloads/research/new_data_r/fy05_1.csv")
#write.csv(fy05_2, "~/Downloads/research/new_data_r/fy05_2.csv")
```


# 2007 
```{r, eval = FALSE}
fy07 <- read_csv("Downloads/research/export/opafy07nid.csv")
fy07_1 <- fy07[,1:9998]
fy07_1$id <- seq.int(nrow(fy07_1))
fy07_2 <- fy07[,9999:19996]
fy07_2$id <- seq.int(nrow(fy07_1)) #1 or 2 doesn't matter, same id 
fy07_3 <- fy07[,19997:24528]
fy07_3$id <- seq.int(nrow(fy07_1))
#write.csv(fy07_1, "~/Downloads/research/new_data_r/fy07_1.csv")
#write.csv(fy07_2, "~/Downloads/research/new_data_r/fy07_2.csv")
#write.csv(fy07_3, "~/Downloads/research/new_data_r/fy07_3.csv")
```


# 2008 

```{r, eval = FALSE}
fy08 <- read_csv("Downloads/research/export/opafy08nid.csv")
fy08_1 <- fy08[,1:9998]
fy08_1$id <- seq.int(nrow(fy08_1))
fy08_2 <- fy08[,9999:15341]
fy08_2$id <- seq.int(nrow(fy08_2))
#write.csv(fy08_1, "~/Downloads/research/new_data_r/fy08_1.csv")
#write.csv(fy08_2, "~/Downloads/research/new_data_r/fy08_2.csv")
```


# 2009 
```{r, eval = FALSE}
fy09 <- read_csv("Downloads/research/export/opafy09nid.csv")
fy09_1 <- fy09[,1:9998]
fy09_1$id <- seq.int(nrow(fy09_1))
fy09_2 <- fy09[,1:9998]
fy09_2$id <- seq.int(nrow(fy09_1))
#write.csv(fy09_1, "~/Downloads/research/new_data_r/fy09_1.csv")
#write.csv(fy09_2, "~/Downloads/research/new_data_r/fy09_2.csv")
```


# 2010 
```{r, eval = FALSE}
fy10 <- read_csv("Downloads/research/export/opafy10nid.csv")
fy10_1 <- fy10[,1:9998]
fy10_1$id <- seq.int(nrow(fy10_1))
fy10_2 <- fy10[,9999:19996]
fy10_2$id <- seq.int(nrow(fy10_1))
fy10_3 <- fy10[,19997:29994]
fy10_3$id <- seq.int(nrow(fy10_1))
fy10_4 <- fy10[,29995:30306]
fy10_4$id <- seq.int(nrow(fy10_1))
#write.csv(fy10_1, "~/Downloads/research/new_data_r/fy10_1.csv")
#write.csv(fy10_2, "~/Downloads/research/new_data_r/fy10_2.csv")
#write.csv(fy10_3, "~/Downloads/research/new_data_r/fy10_3.csv")
#write.csv(fy10_4, "~/Downloads/research/new_data_r/fy10_4.csv")
```


# 2011
```{r, eval = FALSE}
fy11 <- read_csv("Downloads/research/export/opafy11nid.csv")
fy11_1 <- fy11[,1:9998]
fy11_1$id <- seq.int(nrow(fy11_1))
fy11_2 <- fy11[,9999:11467]
fy11_2$id <- seq.int(nrow(fy11_1))
#write.csv(fy11_1, "~/Downloads/research/new_data_r/fy11_1.csv")
#write.csv(fy11_2, "~/Downloads/research/new_data_r/fy11_2.csv")
```

# 2012 
```{r, eval = FALSE}
fy12 <- read_csv("Downloads/research/export/opafy12nid.csv")
fy12_1 <- fy12[,1:9998]
fy12_1$id <- seq.int(nrow(fy12_1))
fy12_2 <- fy12[,9999:18724]
fy12_2$id <- seq.int(nrow(fy12_2))
#write.csv(fy12_1, "~/Downloads/research/new_data_r/fy12_1.csv")
#write.csv(fy12_2, "~/Downloads/research/new_data_r/fy12_2.csv")
```

# 2013 
```{r, eval = FALSE}
fy13 <- read_csv("Downloads/research/export/opafy13nid.csv")
fy13_1 <- fy13[,1:9998]
fy13_1$id <- seq.int(nrow(fy13_1))
fy13_2 <- fy13[,9999:18267]
fy13_2$id <- seq.int(nrow(fy13_1))
#write.csv(fy13_1, "~/Downloads/research/new_data_r/fy13_1.csv")
#write.csv(fy13_2, "~/Downloads/research/new_data_r/fy13_2.csv")
```

# 2014 
```{r, eval =FALSE}
fy14 <- read_csv("Downloads/research/export/opafy14nid.csv")
fy14_1 <- fy14[,1:9998]
fy14_1$id <- seq.int(nrow(fy14_1))
fy14_2 <- fy14[,9999:19996]
fy14_2$id <- seq.int(nrow(fy14_1))
fy14_3 <- fy14[,19997:25001]
fy14_3$id <- seq.int(nrow(fy14_1))
#write.csv(fy14_1, "~/Downloads/research/new_data_r/fy14_1.csv")
#write.csv(fy14_2, "~/Downloads/research/new_data_r/fy14_2.csv")
#write.csv(fy14_3, "~/Downloads/research/new_data_r/fy14_3.csv")
```


# 2015 
```{r, eval = FALSE}
fy15 <- read_csv("Downloads/research/export/opafy15nid.csv")
fy15_1 <- fy15[,1:9998]
fy15_1$id <- seq.int(nrow(fy15_1))
fy15_2 <- fy15[,9999:12819]
fy15_2$id <- seq.int(nrow(fy15_1))
#write.csv(fy15_1, "~/Downloads/research/new_data_r/fy15_1.csv")
#write.csv(fy15_2, "~/Downloads/research/new_data_r/fy15_2.csv")
```

# 2016 
```{r, eval = FALSE}
fy16 <- read_csv("Downloads/research/export/opafy16nid.csv")
fy16_1 <- fy16[,1:9998]
fy16_1$id <- seq.int(nrow(fy16_1))
fy16_2 <- fy16[,9999:19996]
fy16_2$id <- seq.int(nrow(fy16_2))
fy16_3 <- fy16[,19997:22408]
fy16_3$id <- seq.int(nrow(fy16_3))
#write.csv(fy16_1, "~/Downloads/research/new_data_r/fy16_1.csv")
#write.csv(fy16_2, "~/Downloads/research/new_data_r/fy16_2.csv")
#write.csv(fy16_3, "~/Downloads/research/new_data_r/fy16_3.csv")
```

# 2017 
```{r, eval = FALSE}
fy17 <- read_csv("Downloads/research/export/opafy17nid.csv")
fy17_1 <- fy17[,1:9998]
fy17_1$id <- seq.int(nrow(fy17_1))
fy17_2 <- fy17[,9999:19996]
fy17_2$id <- seq.int(nrow(fy17_1))
fy17_3 <- fy17[,19997:20902]
fy17_3$id <- seq.int(nrow(fy17_1))
#write.csv(fy17_1, "~/Downloads/research/new_data_r/fy17_1.csv")
#write.csv(fy17_2, "~/Downloads/research/new_data_r/fy17_2.csv")
#write.csv(fy17_3, "~/Downloads/research/new_data_r/fy17_3.csv")
```

# 2018 
```{r, eval = FALSE}
fy18 <- read_csv("Downloads/research/export/opafy18nid.csv")
fy18_1 <- fy18[,1:9998]
fy18_1$id <- seq.int(nrow(fy18_1))
fy18_2 <- fy18[,9999:19996]
fy18_2$id <- seq.int(nrow(fy18_1))
fy18_3 <- fy18[,19997:27693]
fy18_3$id <- seq.int(nrow(fy18_3))
#write.csv(fy18_1, "~/Downloads/research/new_data_r/fy18_1.csv")
#write.csv(fy18_2, "~/Downloads/research/new_data_r/fy18_2.csv")
#write.csv(fy18_3, "~/Downloads/research/new_data_r/fy18_3.csv")
```

# 2019
```{r, eval = FALSE}

fy19 <- read_csv("Downloads/research/export/opafy19nid.csv")
fy19_1 <- fy19[, 1:9998]
fy19_1$id <- seq.int(nrow(fy19_1))
fy19_2 <- fy19[, 9999:17732]
fy19_2$id <- seq.int(nrow(fy19_2))
#write.csv(fy19_1, "~/Downloads/research/new_data_r/fy19_1.csv")
#write.csv(fy19_2, "~/Downloads/research/new_data_r/fy19_2.csv")

```


# 2020 
```{r, eval = FALSE}
fy20 <- read_csv("Downloads/research/export/opafy20nid.csv")
fy20_1 <- fy20[, 1:9998]
fy20_1$id <- seq.int(nrow(fy20_1))
fy20_2 <- fy20[,9999:16855]
fy20_2$id <- seq.int(nrow(fy20_2))
#write.csv(fy20_1, "~/Downloads/research/new_data_r/fy20_1.csv")
#write.csv(fy20_2, "~/Downloads/research/new_data_r/fy20_2.csv")
```

# 2021 
```{r,eval = FALSE}
fy21 <- read_csv("Downloads/research/export/opafy21nid.csv")
fy21_1 <- fy21[, 1:9998]
fy21_1$id <- seq.int(nrow(fy21_1))
fy21_2 <- fy21[, 9999:19996]
fy21_2$id <- seq.int(nrow(fy21_1)) 
fy21_3 <- fy21[, 19997:20801]
fy21_3$id <- seq.int(nrow(fy21_3))
#write.csv(fy21_1, "~/Downloads/research/new_data_r/fy21_1.csv")
#write.csv(fy21_2, "~/Downloads/research/new_data_r/fy21_2.csv")
#write.csv(fy21_3, "~/Downloads/research/new_data_r/fy21_3.csv")

```

